name: 💡 General Issue
description: A general template for many kinds of issues.
labels: ["status: needs triage"]
body:

- type: textarea
  id: description
  attributes:
    label: Description
    description: |
      Describe what you are proposing, or the question you're asking. Provide as much context as possible and link to related issues and/or pull requests.
      This section should contain "what" you are proposing.
      🐛 If this issue is related to a bug, include information about how to reproduce it and add the `type: bug` label.
      ✨ If this issue is an enhancement or feature, add the `type: enhancement` label.
      ✅ If this issue is a task to complete, add the `type: task` label.
  validations:
    required: true

- type: textarea
  id: tasks
  attributes:
    label: Tasks to complete
    description: |
      Any concrete tasks that should be completed to resolve this issue.
      The more specific the better. If issues have lots of complex tasks associated with them, consider breaking them up into separate issues with cross-links.
      
      _If you can't think of anything then just leave this blank and we can fill it in later! This can be filled in as we understand more about an issue._
    placeholder: |
      - [ ] Discuss and decide on what to do...
      - [ ] Implement partial feature A...
  validations:
    required: false

- type: textarea
  id: updates
  attributes:
    label: Updates
    description: |
      To avoid that others have to read through the full thread of comments, please update the initial issue with important updates (e.g. decisions taken) regularly. You can update any of the sections above directly (this is encouraged!) or add new information below in this new section.
      _If you can't think of anything then just leave this blank and we can fill it in later! This can be filled in as we understand more about an issue._
  validations:
    required: false