name: 📝 New content proposal
description: Do you have a new idea for content?
labels: ["type: new content 📝 "]
body:


- type: textarea
  id: description
  attributes:
    label: Description
    description: |
      Please provide a description of the content you are writing or proposing. Thing about the following:
      - What is the purpose of the new content?
      - Why are you proposing it?
      - Have you started any PRs for this? If so link to it
  validations:
    required: true

- type: textarea
  id: resources
  attributes:
    label: Resources
    description: |
      List and describe any external resouces that might be helpful to write the content. We suggest using bullets (indicated by * or -) and filled checkboxes [x] here
  validations:
    required: false

- type: textarea
  id: updates
  attributes:
    label: Updates
    description: |
      To avoid that others have to read through the full thread of comments, please update the initial issue with important updates (e.g. decisions taken) regularly. You can update any of the sections above directly (this is encouraged!) or add new information below in this new section.
      _If you can't think of anything then just leave this blank and we can fill it in later! This can be filled in as we understand more about the content._
  validations:
    required: false